namespace WarringStates.Net.Common;

public enum ServiceCode
{
    None,
    Success,
    UnknowError,
    UnknownCommand,
    UnknownOperate,
    MissingCommandArgs,
    WrongPassword,
    MultiPlayerName,
    EmptyPlayerName,
    EmptyPassword,
    NotLogined,
    PlayerAlreadyLogined,
    WrongProtocolType,
    SameVersionAlreadyExist,
    CannotAddFileToProcess,
    FileExpired,
    NotSameVersion,
    FileNotExist,
    PlayerNotExist,
    ServerNotStartYet,
    ServerHasStarted,
    CannotFindSourceSendCommand,
    CannotAddCommandWaitingForCallback,
    CannotFindSourceCommandToCompose,
    CannotAddCommandWaitingForCompose,
    EmptyUserInfo,
    NoConnection,
    NoMatchArchiveId,
}
